"""Add location address

Revision ID: 680f6ce67ae2
Revises: c76b3e1bd982
Create Date: 2022-10-28 21:51:05.213738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680f6ce67ae2'
down_revision = 'c76b3e1bd982'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('location_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'location_address')
    # ### end Alembic commands ###
