"""Remove location table

Revision ID: 69cf86864a0e
Revises: 7b98c235f294
Create Date: 2022-11-15 02:01:48.269975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cf86864a0e'
down_revision = '7b98c235f294'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Location',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Location_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Location_pkey')
    )
    # ### end Alembic commands ###
