"""Modify location ID type temporarily

Revision ID: 7b98c235f294
Revises: ab63f73042bd
Create Date: 2022-11-15 01:59:07.041108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b98c235f294'
down_revision = 'ab63f73042bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
