"""Re-add location table

Revision ID: 8f9c6b3ba0a5
Revises: 69cf86864a0e
Create Date: 2022-11-15 02:02:26.390921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f9c6b3ba0a5'
down_revision = '69cf86864a0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Location',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Location')
    # ### end Alembic commands ###
